const insert = document.querySelector('.insert')
window.addEventListener('keypress', (e) => {
    insert.innerHTML = `
    <h2>HTML Table</h2>
    <table>
        <tr>
            <th>Key</th>
            <th>Key Code</th>
            <th>Code</th>
        </tr>
        <tr>
            <td>${e.key == ' ' ? 'Space' : e.key}</td>
            <td>${e.keyCode}</td>
            <td>${e.code}</td>
        </tr>        
    </table>`;
})
// Save button functionality
// let saveButton = document.getElementById('saveBtn');
// saveButton.addEventListener('click', ()=>{
    // Get all items from the list as array
//     let arrItems = Array.from(itemsList.getElementsByTagName('li'));
    // Prepare data for saving into local storage
//     let dataToSave = {};
    // For every item in the list create a key-value pair where key is text content of current item and value is its id (which will be assigned later). Ids are generated by taking the index of the item in the array + 1 because ids should start with 1 not 0. If there are no items in the list assign id 1
//     arrItems.forEach((el, i)=>{
//         dataToSave[i+1] = el.textContent;
//         });
        // Assign unique id for each item in the list
//         let maxId = Math.max(...Object.keys(dataToSave));
//         for(let key in dataToSave){
//             dataToSave[key].id = maxId + key;
//         }
        // Save data into local storage
//         localStorage.setItem('todoList', JSON.stringify(dataToSave))
// })
    // Load saved data from local storage and display it on the page